export const WRITE_SCAN_DETAILS_REQUEST = "WRITE_SCAN_DETAILS_REQUEST";
export const WRITE_SCAN_DETAILS_SUCCESS = "WRITE_SCAN_DETAILS_SUCCESS";
export const WRITE_SCAN_DETAILS_FAILURE = "WRITE_SCAN_DETAILS_FAILURE";
export const FETCH_SCAN_LIST_REQUEST = "FETCH_SCAN_LIST_REQUEST";
export const FETCH_SCAN_LIST_SUCCESS = "FETCH_SCAN_LIST_SUCCESS";
export const FETCH_SCAN_LIST_FAILURE = "FETCH_SCAN_LIST_FAILURE";
export const SCAN_TIMEOUT = 5000;